#! /bin/bash

confirm="y"
installReply="install"
updateReply="update"
fullInstall=0
read -p "What you wanna do bro ? [install/update] :" -r;
if [ "$REPLY" == "$installReply" ]; then
    fullInstall=1
fi
if [ "$REPLY" != "$updateReply" ]; then
    echo "sry I didn't understand what you said, bai";
    exit;
fi
if [ "$fullInstall" = "0"]; then
    sudo apt update;
    sudo apt upgrade -y;
    echo "Done.";
    git clone git@github.com:echoffee/comfy-env.git;
    success=$?;
    if [ "$success" != "0" ]; then
        echo "Repo couldn't be cloned. Did you set the SSH Key ? You can re-run this script once it's been fixed.";
        exit;
    fi
    cp -r comfy-env/bin comfy-env/config .;
    cp -r comfy-env/.vimrc comfy-env/.bashrc comfy-env/.gitconfig  .;
    cp -r comfy-env/colorschemes/mintty ./colors-for-mintty;
    cp -r comfy-env/colorschemes/win-terminal ./colors-for-win-terminal;
    rm -rf comfy-env;
    echo " run 'rez' to update the shell";
    exit;
fi
read -p "This script will install a bunch of stuff, u ready ? [y/n] :" -r;
if [ "$REPLY" != "$confirm" ]; then
    echo "k no prob, bai";
    exit;
fi
ow=1
if [ -z "$sshpath" ]
then
    read -p "Generate SSH key ? (~/.ssh/id_rsa) [y/n] :" -r;
    if [ "$REPLY" != "$confirm" ]; then
        ow=0
    fi
fi
echo "A prompt will maybe ask you if it's okay to restart services and stuff";
echo "Select 'Yes' on it. Press Enter to continue...";
read;
sudo apt update;
sudo apt upgrade -y;
if [ "$ow" = "1" ]; then
    ssh-keygen -f ~/.ssh/id_rsa;
fi
cd;
cat ~/.ssh/id_rsa.pub | clip.exe;
echo "Public SSH key copied into clipboard. Go to GitHub and add this key to the list. (Github Profile > Settings > SSH and GPG keys)";
read -p "Once it's done, type 'y' :" -r;
if [ "$REPLY" != "$confirm" ]; then
    echo "Aborted.";
    exit;
fi

git clone git@github.com:echoffee/comfy-env.git;
success=$?;
if [ "$success" != "0" ]; then
    echo "Repo couldn't be cloned. Did you set the SSH Key ? You can re-run this script once it's been fixed.";
    exit;
fi
cp -r comfy-env/bin comfy-env/config .;
cp -r comfy-env/.vimrc comfy-env/.bashrc comfy-env/.gitconfig  .;
cp -r comfy-env/colorschemes/mintty ./colors-for-mintty;
cp -r comfy-env/colorschemes/win-terminal ./colors-for-win-terminal;
rm -rf comfy-env;

git clone git@github.com:echoffee/vimwiki.git;

sudo apt install ranger -y;

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf;
~/.fzf/install;

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim ;

read -p "Set links to drives directly at / ? [y/n]" -r
if [ "$REPLY" = "$confirm" ]; then
    ln -s /mnt/* .;
fi

clear;
echo " comfy environnement set !"
echo " run 'source .bashrc' to update the shell";
echo " run 'vim +PlugInstall' on the first start to download and install its plugins. The startup error about a missing 'comfy' thing is normal and will be fixed after that.";
